### ISSUE TITLE
Comunicación entre widgets

### ISSUE THREAD

**Issue by tomasregna** [tomasregna/WOW#30]
En este código comentado, intenté sin éxito expresar, dentro de una ventana (un widget) llamada menuPrincipal, que cerrara otra ventana previamente abierta:

https://github.com/tomasregna/WOW/blob/92d26e97308cecbeb24ce5086aae19b3a85c3fdc/testgrafico.py#L61

Lo sumamente extraño, es que al entrar a esa ventana, le pedí que eliminara el widget de raiz, root, y no tuvo ningún problema. Ahora, parado acá, en winInfo -otro widget-, el programa debería eliminar el widget menuPrincipal, pero dice que no conoce nada llamado así ...

La investigación me dice que es:
1. Un problema en mi entendimiento de las clases **[MUY PROBABLE]**
2. Un problema de jerarquizar las clases Tk() y Toplevel(). Ya que Tk() es la principal de las principales, en algún lado aconsejaron que la abra una sola vez, y como verás, la abrí siempre (pero no lleva a errores sorprendentemente), mientras que tratando de ponerle jerarquías a los widgets, Toplevel() interfiere de alguna manera y abre los demás widgets sin que se lo pida.

No sé cómo encontrar la manera de hacerle recordar a un widget, la existencia de otro, para poder interactuar -llámesele borrar al anterior-.

**Comment by nguevara** [comment]
Migración a PyQT, issue no aplica.
