### ISSUE TITLE
Potencial problema con las aperturas del phot

### ISSUE THREAD

**Issue by tomasregna** [tomasregna/WOW#32]
Problemilla para imprimir el segundo radio de apertura, que justo apareció en la exposición.

(Corroborar si es o no un bug)

**Comment by nguevara** [comment]
Por alguna razón, hace un solo radio de apertura aunque debiera hacer 2 !

**Comment by nguevara** [comment]
El problema estaba en que le estaba pasando un array (transformado en string), y confundía a iraf. Además, el fwhm estaba expresaado como punto flotante con muchos decimales.
