### ISSUE TITLE
Agregar gain + rdnoise + otros al reduc

### ISSUE THREAD

**Issue by tomasregna** [tomasregna/WOW#33]
Colgamos con eso; habría que ver también que otras cosas importantes podríamos estar salteando sin querer...

**Comment by nguevara** [comment]
rdnoise: probe con imágenes de CASLEO del año 2018, tomadas durante una observación remota en la cátedra de Observacional. No me tiró el error del rdnoise. Debemos haberlo probado con las imágenes de  la práctica que deliberadamente les faltaba ese dato en el header.

**Comment by nguevara** [comment]
Las imagenes del HSH tienen el gain y el rdnoise en el header.
JS no, hay que agregarlo manual
